export default{
    name:"Shima Soltani",
    home:"HOME",
about:"ABOUT",
resume:"RESUME",
portfolios:"PORTFOLIOS",
cintact:"CONTACT",
hi:"Hi, I am ",
hi2:"",
desc:"i am a frontend web developer.i provide clean code and pixel perfect design.i also make website more & more intractive whit web animations.",
aboutme:"ABOUT ME ",
services:"SERVICE ME",
 fullname:"Full Name",
 age:"Age",
 nationalty:"Nationalty",
 languages:"Languages",
 phone:"Phone",
 download:"DOWNLOAD VC",
 iranian:"Iranian",
 persian:"Persian,English",
 descphone:"It costs a lot to design a site and the possibility of online conversation",
 titlephone:"Aplication Mobile",
 webdesign:"Web Design",
descdesign:"Website design is an attractive and widely used job.i love web designer",
webdevelopment:"Web Development",
titledevelopment:"i am a frontend web developer and i provide clean code.i like web developer",
myskill:"MY SKILLS",
javaScript:"javaScript",
html:"HTML5",
node:"NODE.JS",
reactjs:"React js",
php:"PHP",
reactnative:"React Native",
workingSteps:  [  { id: -1, date: "", title: "", subtitle: "", content: "" },
{ id: 0, date: "2018 - 2019", title: "BackEnd Web developer", subtitle: "Abc Univercity", content: "We bring the flow to your software team's workflow. Plan, collaborate, build, and measure success with Shortcut." },
{ id: 1, date: "2018 - 2019", title: "FrontEnd Web developer", subtitle: "Abc Univercity", content: "We bring the flow to your software team's workflow. Plan, collaborate, build, and measure success with Shortcut." },
{ id: -2, date: "", title: "", subtitle: "", content: "" }],
educationalSteps:  [  { id: -1, date: "", title: "", subtitle: "", content: "" },
{ id: 0, date: "2018 - 2019", title: "master of Science", subtitle: "Abc Univercity", content: "We bring the flow to your software team's workflow. Plan, collaborate, build, and measure success with Shortcut." },
{ id: 1, date: "2018 - 2019", title: "Bachelor of Science", subtitle: "Abc Univercity", content: "We bring the flow to your software team's workflow. Plan, collaborate, build, and measure success with Shortcut." },
{ id: 2, date: "2018 - 2019", title: "High School Graduation", subtitle: "Abc Univercity", content: "We bring the flow to your software team's workflow. Plan, collaborate, build, and measure success with Shortcut." },
{ id: -2, date: "", title: "", subtitle: "", content: "" }],
workingexperience:"Working Experience",
educationalqualifications:"Educational qualifications"
}